services:
  backend:
    environment:
      NODE_ENV: production
      FRONTEND_DIR: /app/frontend
    restart: always
    volumes:
      - ./frontend:/app/frontend:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

  db:
    restart: always
